### ISSUE TITLE
Fix for missing default (light) gnome-shell theme

### ISSUE THREAD

**Issue by seyfert** [fkohlgrueber/yaru-anycolor#1] opened 2020-05-02 20:10 UTC
First, thanks for sharing this project. The first thing I did after installing 20.04 was search for a way to change the default colors of Yaru and I think this is the best approach I've seen.

It appears that the "Default" shell theme is still  the standard Yaru colors even after choosing a different application theme. I installed the [User Themes](https://extensions.gnome.org/extension/19/user-themes/) but didn't allow me to choose "YaruBlue" from the dropdown (I prefer to have a dark application theme and light shell theme).

![image](https://user-images.githubusercontent.com/2137082/80889744-5b169600-8c84-11ea-9c81-25f530bf3e07.png)

![image](https://user-images.githubusercontent.com/2137082/80890809-5ef6e800-8c85-11ea-8f58-7a1f62ad724b.png)

I was able to fix it by simply removing the gnome-shell-gresource parameter when building.
```
meson build
```

When gnome-shell-gresource is true, the build process will not copy the files gnome-shell.css and gnome-shell-high-contrast.css into `/usr/share/themes/[THEME NAME]/gnome-shell`.

Hope someone else finds this helpful.

**Comment by fkohlgrueber** [comment] 2020-05-15 13:31
Hi seyfert,

I'm sorry for taking so long to respond. I somehow didn't get a notification that you've opened this issue. I'll try to change the settings so that this doesn't happen again.

It is possible to change the shell theme without installing the User themes extension. On the login screen, there's an icon in the bottom right corner. This usually lets you choose between X11 and Wayland sessions, but after installing YaruBlue, it also contains entries for using YaruBlue instead of the standard Ubuntu shell theme. Change this to YaruBlue, and the "default" user shell theme should be YaruBlue(-light). The application theme can be changed independently to whatever you want.

![screenshot](https://user-images.githubusercontent.com/9519668/82055486-dd5d7c00-96c0-11ea-92f5-11619282915c.png)

Does this solve your problem?

**Comment by fkohlgrueber** [comment] 2020-07-28 15:53
@seyfert I'm closing this issue, but feel free to reopen if the issue is still there for you.

**Closed as completed by fkohlgrueber** 2020-07-28 15:53 UTC
